server:
  port: 8033

spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mvc:
    hiddenmethod:
      filter:
        enabled: false
